### ISSUE TITLE
博文中标题#的显示问题

### ISSUE THREAD

**Issue by mttzxm** [loveminimal/hexo-theme-zero#1]
![image](https://user-images.githubusercontent.com/18676754/56265932-808a3d80-611d-11e9-9f53-989f177cdb5c.png)

style中对于标题的样式在博文中显示了颜色修改，但是# 符号也跟着显示了，这样该怎么修改呢？
![image](https://user-images.githubusercontent.com/18676754/56265875-62244200-611d-11e9-9880-ba9d9bde43f4.png)

**Comment by loveminimal** [comment]
Hey，有些忙，刚看到 ：）

- 目前，`#`  是通过伪类直接加在标题前面的，所以它们的颜色总是保持一致的。
- 加上 `#`  的原因是为了方便区分标题等级，低级标题和加粗行。

如果，你十分需要单独只改变标题内容的颜色，需要修改对应的 `ejs` 模板，把标题内容用一个 `span` 元素包起来，单独设置样式。

**Comment by loveminimal** [comment]
> ![image](https://user-images.githubusercontent.com/18676754/56265932-808a3d80-611d-11e9-9f53-989f177cdb5c.png)
> 
> style中对于标题的样式在博文中显示了颜色修改，但是# 符号也跟着显示了，这样该怎么修改呢？
> ![image](https://user-images.githubusercontent.com/18676754/56265875-62244200-611d-11e9-9880-ba9d9bde43f4.png)

Hey，有些忙，刚看到 ：）

- 目前，`#` 是通过伪类直接加在标题前面的，所以它们的颜色总是保持一致的。
- 加上 `#` 的原因是为了方便区分标题等级，低级标题和加粗行。

如果，你十分需要单独只改变标题内容的颜色，需要修改对应的 `ejs` 模板，把标题内容用一个 `span` 元素包起来，单独设置样式。^_^
