### ISSUE TITLE
配置文档

### ISSUE THREAD

**Issue by blueoblue** [loveminimal/hexo-theme-zero#4]
主题配置文档能不能增加说明，比如如何添加新的配置项，网页样式的更改等。。

**Comment by blueoblue** [comment]
还有页面不能显示markdown

**Comment by loveminimal** [comment]
> 还有页面不能显示markdown

这个主题并不具备 `Next` 主题那样强力的可扩展性，如果需要更改样式，就需要自己去修改相应的样式文件 ^_^

---

不能显示 markdown ? 这个可能是由于写入了一些错误配置，部署了吗，可以把网址贴出来我看一下
