### ISSUE TITLE
按钮显示乱码 & 背景图片如何修改

### ISSUE THREAD

**Issue by hongling-dev** [loveminimal/hexo-theme-zero#5]
您好，谢谢您写了如此清新、优雅的 hexo 主题！！！

在部署后，遇到两个问题

1、按钮显示乱码，并且显示了两行

![image](https://user-images.githubusercontent.com/28445132/84143545-56b27980-aa89-11ea-917d-99773ce247f4.png)

2、背景图片如何修改？

![image](https://user-images.githubusercontent.com/28445132/84143597-6f229400-aa89-11ea-9b5d-43418d8a33cb.png)

期待您的回复，谢谢！

**Comment by loveminimal** [comment]
> 您好，谢谢您写了如此清新、优雅的 hexo 主题！！！
> 
> 在部署后，遇到两个问题
> 
> 1、按钮显示乱码，并且显示了两行
> 
> ![image](https://user-images.githubusercontent.com/28445132/84143545-56b27980-aa89-11ea-917d-99773ce247f4.png)
> 
> 2、背景图片如何修改？
> 
> ![image](https://user-images.githubusercontent.com/28445132/84143597-6f229400-aa89-11ea-9b5d-43418d8a33cb.png)
> 
> 期待您的回复，谢谢！

So sorry :  ) 
刚看到，很高兴你喜欢使用它。
可以附上你的 web 地址吗，和具体页面吗？我需要用它调试下。

换背景看下这个： https://github.com/loveminimal/hexo-theme-zero/issues/6
