### ISSUE TITLE
how to change background picture?

### ISSUE THREAD

**Issue by Syize** [loveminimal/hexo-theme-zero#6]
Hi! Very beautiful theme! 
I saw there are some differences between screenshot and the reality, like the background picture. 
Can you tell me if there any way to change the picture?
Thank you!

**Comment by loveminimal** [comment]
> Hi! Very beautiful theme!
> I saw there are some differences between screenshot and the reality, like the background picture.
> Can you tell me if there any way to change the picture?
> Thank you!

---

In this following file:  
https://github.com/loveminimal/hexo-theme-zero/blob/master/source/css/style.styl

```stylus
body
  margin: 0
  padding: 0
  // background: #1E1F20 url(/images/snow.gif) fixed
  // background: honeydew
  background:#fdfdfd -200px 30% url(../images/man.gif) fixed no-repeat
  // background-size: 25%
```

In NO.54 , Just update  `url(../images/man.gif)` to that you like. 

And there has some other pictures in this directory:
https://github.com/loveminimal/hexo-theme-zero/tree/master/source/images

**Comment by Syize** [comment]
Thank you!
