### ISSUE TITLE
'#' in title

### ISSUE THREAD

**Issue by Syize** [loveminimal/hexo-theme-zero#7]
Hey bro, I also found some questions.
The '#' in title doesn't disappear.
![2020-07-31 23-45-17屏幕截图](https://user-images.githubusercontent.com/44666294/89052287-11733f80-d388-11ea-9ac3-c661864b932a.png)
Is this wrong or this is one of the theme's character?

**Comment by loveminimal** [comment]
> Hey bro, I also found some questions.
> The '#' in title doesn't disappear.
> ![2020-07-31 23-45-17屏幕截图](https://user-images.githubusercontent.com/44666294/89052287-11733f80-d388-11ea-9ac3-c661864b932a.png)
> Is this wrong or this is one of the theme's character?

`#` in the headers ?

If yes, it will be YES. : ) It's a flag of header level.
